shoesdepot/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import PasswordResetView

urlpatterns = [
    path('', include('shoesdepot.store.urls')),
    path('admin/', admin.site.urls),
    path('user/', include('shoesdepot.app_auth.urls')),
    path('cart/', include('shoesdepot.cart.urls')),
    path('store_admin/', include('shoesdepot.store_admin.urls')),
    path('orders/', include('shoesdepot.orders.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shoesdepot/store/models.py
from django.db import models
from django.utils.text import slugify
from .validators import validate_product_price


class Category(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(unique=True, blank=True, editable=False)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if not self.slug:
            self.slug = slugify(f'{self.id}-{self.name}')
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.parent.name} {self.name}" if self.parent else self.name


class Size(models.Model):
    name = models.CharField(max_length=10, unique=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    price = models.DecimalField(max_digits=6, decimal_places=2, validators=[validate_product_price])
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='products')
    is_on_sale = models.BooleanField(default=False)
    sale_price = models.DecimalField(max_digits=6, decimal_places=2, blank=True, null=True,
                                     validators=[validate_product_price])
    sizes = models.ManyToManyField(Size, through='ProductSize')
    slug = models.SlugField(unique=True, blank=True, editable=False)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if not self.slug:
            self.slug = slugify(f'{self.id}-{self.name}')
        super().save(*args, **kwargs)

    def get_discount_percent(self):
        if not self.sale_price or not self.price:
            return 0

        discount = (self.price - self.sale_price) / self.price
        return round(discount * 100, 0)

    def __str__(self):
        return self.name


class ProductSize(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    size = models.ForeignKey(Size, on_delete=models.CASCADE)

templates/401.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <!-- Section-->
    <section class="pb-xxl-5 pt-xxl-3">
        <div class="container bg-white py-xxl-5 rounded-3 shadow">
            <div class="display-5 text-center py-xxl-5 my-xxl-5">
                <h2>401 - Unauthorized</h2>
                <p>You are not authorized to access this page. Please log in.</p>
            </div>
        </div>
    </section>
{% endblock %}







templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>SHOESDEPOT</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}"/>
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    {% block head %}
    {% endblock %}
</head>
<body>
{% include 'navbar.html' %}
<div class="bg-light pt-4">
    {% block content %}
    {% endblock %}
</div>
<!-- Footer-->
<div class="container">
    <footer class="row row-cols-1 row-cols-sm-2 row-cols-md-5 py-5 my-5 border-top">
        <div class="col mb-3 text-center">
            <a href="#" class="d-flex align-items-center mb-3 link-body-emphasis text-decoration-none">
                <img src="{% static 'logo.png' %}" alt="" height="150">
            </a>
            <p class="text-body-secondary">SHOESDEPOT © 2024</p>
        </div>
        <div class="col mb-3"></div>
        <div class="col mb-3">
            <h5>Section</h5>
            <ul class="nav flex-column">
                <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Home</a></li>
                <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Features</a></li>
                <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Pricing</a></li>
                <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">FAQs</a></li>
                <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">About</a></li>
            </ul>
        </div>
        <div class="col mb-3">
            <h5>Section</h5>
            <ul class="nav flex-column">
                <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Home</a></li>
                <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Features</a></li>
                <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Pricing</a></li>
                <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">FAQs</a></li>
                <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">About</a></li>
            </ul>
        </div>
        <div class="col mb-3">
            <h5>Section</h5>
            <ul class="nav flex-column">
                <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Home</a></li>
                <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Features</a></li>
                <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">Pricing</a></li>
                <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">FAQs</a></li>
                <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-body-secondary">About</a></li>
            </ul>
        </div>
    </footer>
</div>
{#<!-- Bootstrap core JS-->#}
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"
        integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy"
        crossorigin="anonymous"></script>
</body>
</html>

templates/breadcrumb.html
{% load static %}
<nav style="--bs-breadcrumb-divider: '>';" aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a class="link-body-emphasis" href="{% url 'home' %}"><i class="bi bi-house-door-fill"></i><span
                    class="visually-hidden">Home</span></a>
        </li>
        {% if product.category %}
            <li class="breadcrumb-item">
                <a class="link-body-emphasis fw-semibold text-decoration-none"
                   href="{% url 'category_details' product.category.parent.slug 'all' %}">{{ product.category.parent.name }}</a>
            </li>
            <li class="breadcrumb-item">
                <a class="link-body-emphasis fw-semibold text-decoration-none"
                   href="{% url 'category_details' product.category.parent.slug product.category.slug %}">
                    {{ product.category.name }}</a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">
                {{ product.name }}
            </li>
        {% elif main_category %}
            <li class="breadcrumb-item">
                <a class="link-body-emphasis fw-semibold text-decoration-none"
                   href="{% url 'category_details' main_category.slug 'all' %}">{{ main_category.name }}</a>
            </li>
            {% if subcategory %}
                <li class="breadcrumb-item active" aria-current="page">
                    {{ subcategory }}
                </li>
            {% else %}
                <li class="breadcrumb-item active" aria-current="page">
                    All
                </li>
            {% endif %}
        {% endif %}
    </ol>
</nav>

templates/navbar.html
{% load static %}
<!-- Navigation-->
<nav class="navbar navbar-expand-lg bg-white">
    <div class="container container-fluid">
        <!-- Logo -->
        <a class="text-decoration-none fw-bolder me-3" href="{% url 'home' %}">
            <span style="color: red; font-size: 25px;">SHOES</span><span
                style="color: black; font-size: 25px;">DEPOT</span>
        </a>
        <!-- Menu -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-lg-0">
                {% for category in categories %}
                    {% if category.parent_id is Null %}
                        <div class="dropdown">
                            <a class="text-decoration-none me-2 fs-3" href="#" role="button"
                               data-bs-toggle="dropdown" aria-expanded="false">
                                {{ category.name }}
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item"
                                       href="{% url 'category_details' category.slug  'all' %}">All
                                    {{ category.name }}</a></li>
                                {% for child_category in category.category_set.all %}
                                    <a class="dropdown-item"
                                       href="{% url 'category_details' category.slug child_category.slug %}">{{ child_category.name }}</a>
                                {% endfor %}
                            </ul>
                        </div>
                    {% endif %}
                {% endfor %}
            </ul>
            <form class="d-flex me-auto" method="GET" action="{% url 'home' %}">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="search_query">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
        <!-- Profile -->
        <a href="{% url 'profile' %}"><i class="bi bi-person text-dark fs-2 pe-2"></i></a>
        {% if user.is_authenticated %}
            <a href="{% url 'logout_user' %}"><i class="bi bi-box-arrow-right text-dark fs-2 pe-2"></i></a>
        {% endif %}
        <!-- Sopping Cart -->
        <div class="position-relative pb-1">
            <a href="{% url 'cart_summary' %}"><i class="bi bi-cart2 text-dark fs-2"></i></a>
            <span class="position-absolute mt-2 top-0 start-100 translate-middle badge rounded-pill bg-danger"
                  id="cart_qty"
                  style="{% if request.session.cart_items_count == 0 or request.session.cart_items_count == None %} display: none; {% endif %}">
                {{ request.session.cart_items_count }}</span>
        </div>
        <!-- Toggle -->
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    </div>
</nav>

templates/pagination.html
{% if paginator.num_pages > 1 %}
    <nav class="pb-3">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}
{% if request.GET.sort %}&sort={{ request.GET.sort }}
{% elif request.GET.pk %}&pk={{ request.GET.pk }}
{% elif request.GET.category %}&category={{ request.GET.category }}
{% elif request.GET.search_query %}&search_query={{ request.GET.search_query }}{% endif %}">Previous</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <span class="page-link">Previous</span>
                </li>
            {% endif %}
            {% for page_num in paginator.page_range %}
                <li class="page-item {% if page_num == page_obj.number %}active{% endif %}">
                    <a class="page-link" href="?page={{ page_num }}
{% if request.GET.sort %}&sort={{ request.GET.sort }}
{% elif request.GET.pk %}&pk={{ request.GET.pk }}
{% elif request.GET.category %}&category={{ request.GET.category }}
{% elif request.GET.search_query %}&search_query={{ request.GET.search_query }}{% endif %}">{{ page_num }}</a>
                </li>
            {% endfor %}
            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}
{% if request.GET.sort %}&sort={{ request.GET.sort }}
{% elif request.GET.pk %}&pk={{ request.GET.pk }}
{% elif request.GET.category %}&category={{ request.GET.category }}
{% elif request.GET.search_query %}&search_query={{ request.GET.search_query }}{% endif %}">Next</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <span class="page-link">Next</span>
                </li>
            {% endif %}
        </ul>
    </nav>
{% endif %}

templates/template.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <!-- Section-->
    <section>
        <div class="container px-4 px-lg-5">

            
            
        </div>
    </section>
{% endblock %}